from google.adk.agents import Agent
from google.adk.sessions import InMemorySessionService
from google.adk.agents.callback_context import CallbackContext
from google.adk.models.llm_request import LlmRequest
from google.adk.models.llm_response import LlmResponse
from google.adk.runners import Runner
from google.genai import types
from typing import Optional
import asyncio

from dotenv import load_dotenv
load_dotenv()

callback_log = []
response_metrics = []

DISCLAIMER = "\n\n_[Disclaimer: This response was generated by AI and may not be 100% accurate.]_"

#Callback 1
def log_request(callback_context: CallbackContext, llm_request: LlmRequest) -> Optional[LlmRequest]:
    agent_name = callback_context.agent_name
    
    last_user_message = ""
    if llm_request.contents:
        for content in reversed(llm_request.contents):
            if content.role == "user" and content.parts:
                if content.parts[0].text:
                    last_user_message = content.parts[0].text
                    break
        
    total_messages = len(llm_request.contents) if llm_request.contents else 0
    
    log_entry = {
        "agent": agent_name,
        "total_messages": total_messages,
        "last_user_message": last_user_message[:80]
    }
    callback_log.append(log_entry)
    
    print(f" [BEFORE MODEL] Messages in context: {total_messages}")
    print(f"[BEFORE MODEL] Latest user message: '{last_user_message[:80]}'")
    
    return None


#Callback 2
def monitor_response(callback_context: CallbackContext, llm_response: LlmResponse) -> Optional[LlmResponse]:
    
    response_text = ""
    if llm_response.content and llm_response.content.parts:
        for part in llm_response.content.parts:
            if part.text:
                response_text += part.text
                
    word_count = len(response_text.split())
    char_count = len(response_text)
    
    response_metrics.append({
        "word_count": word_count,
        "char_count": char_count,
        "preview": response_text[:60]
    })
    
    print(f"[AFTER MODEL] Response Length: {word_count} words, {char_count} chars")
    
    if response_text:
        modified_text = response_text + DISCLAIMER
        print(f"[AFTER MODEL] Disclaimer appended")
        
        return LlmResponse(
            content=types.Content(
                role="model",
                parts=[types.Part(text=modified_text)]
            )
        )
        
    return None


agent = Agent(
    model="gpt-4o-mini",
    name="logging_agent",
    description="A helpful assistant with request logging and response monitoring",
    instruction="""You are a concise assistant. Answer questiosn in 1-2 sentences""",
    before_model_callback=log_request,
    after_model_callback=monitor_response
)

session_service = InMemorySessionService()
APP_NAME = "model callback demo"
USER_ID = "user_1"
SESSION_ID = "session_1"

runner = Runner(
    agent=agent,
    app_name=APP_NAME,
    session_service=session_service
)

asyncio.run(
    session_service.create_session(
        app_name=APP_NAME, user_id=USER_ID, session_id=SESSION_ID
    )
)


def call_agent(query: str):
    print(f"\n>>> User: {query}")
    
    # Wrap User Query as a Content Object
    message = types.Content(role="user", parts=[types.Part(text=query)])
    
    final_response = "No response received"
    for event in runner.run(user_id=USER_ID, session_id=SESSION_ID, new_message=message):
        if event.is_final_response():
            if event.content and event.content.parts:
                final_response = event.content.parts[0].text
                
    print(f"<<< Agent: {final_response}")
    


print("=" * 60)
print("Model Callbacks - Request Logging & Response Monitoring")
print("=" * 60)

call_agent("What is the speed of light?")
call_agent("How far is the Moon from Earth")
call_agent("What causes earthquakes")

